"""
Live agricultural task service -- HARVEST's task layer for the live stack.

WHAT THIS IS, AND WHAT IT DELIBERATELY IS NOT.  It is the bridge between the
task model HARVEST already has (``main.Task``, generated by
``task_generator`` and assigned by ``main.Scheduler``) and the *live* fleet that
the HTTP API, FIWARE, ROS 2 and Isaac Sim all see.  It is NOT a second
scheduler: task creation comes from :func:`main.build_simulation_config` and
every assignment decision comes from :meth:`main.Scheduler.assign_tasks` --
priorities, deadlines, preemption, relaxed windows and the tractor-scoring
policy are HARVEST's existing logic, called, not reimplemented.  A second
scheduler is exactly the thing that would make the demonstrator disagree with
the simulated day it is supposed to demonstrate.

The division of labour with the physical layer (Isaac Sim), which is the point
of the whole exercise:

* HARVEST creates tasks, decides which tractor does which one and when, owns
  priorities and deadlines, and DECLARES a task complete;
* Isaac Sim is told where a task is and how long the work takes, drives the
  tractor there, runs the work, and REPORTS what physically happened;
* this service turns those reports into task-phase transitions, and falls back
  to its own clock-based accounting when no simulator is connected -- so the
  task layer works in every mode, and Diagnostics always says which of the two
  is driving it.

Charging is not special-cased here.  ``Scheduler.assign_tasks`` already refuses
to hand work to a charging tractor (except a well-charged one as a last resort,
which it then releases from the charger), and the fleet backend already refuses
to send a tractor with an active task to a charger.  Both of those are HARVEST's
existing rules and this service simply lets them apply.
"""
from __future__ import annotations

import os
import sys
import threading
import time
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from harvest_control.interface import Command, FleetSnapshot

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

#: Task phases, as HARVEST's own model names them, mapped to the five states the
#: demonstrator shows.  The mapping lives in the simulator contract so both ends
#: agree on the vocabulary; see ``simulators/isaac/contract.py``.
from harvest_integrations.simulators.isaac.contract import (   # noqa: E402
    TASK_STATES, task_state_from_phase,
)

#: How long a physical progress report stays authoritative.  Past this the
#: service falls back to its own clock -- a simulator that died mid-task must not
#: freeze the farm's work for ever.
PHYSICAL_STALE_S = 12.0

#: A tractor is "at" its task within this radius (metres).  The simulator uses
#: the same number for its own arrival test, from the command message, so the
#: two cannot disagree about what arriving means.
DEFAULT_WORK_RADIUS_M = 6.0

#: Wall-clock seconds per simulated minute of work.  1.0 matches the live farm
#: clock (``integrations.fleet.sim_minutes_per_s``), so a 30-minute task takes
#: 30 s to watch and HARVEST's clock-based progress and the simulator's
#: wall-clock work timer agree without either having to know about the other.
DEFAULT_SECONDS_PER_WORK_MINUTE = 1.0


class LiveTaskService:
    """HARVEST's live task layer.  Thread-safe; ticks on its own thread."""

    def __init__(self, raw_cfg: Dict[str, Any], runtime: Any,
                 *, tick_period_s: float = 1.0):
        import main                                            # noqa: PLC0415

        self._runtime = runtime
        self._lock = threading.RLock()
        self._stop = threading.Event()
        self._raw = raw_cfg

        settings = (raw_cfg.get("integrations") or {}).get("tasks") or {}
        self.work_radius_m = float(settings.get(
            "work_radius_m", DEFAULT_WORK_RADIUS_M))
        self.seconds_per_work_minute = float(settings.get(
            "seconds_per_work_minute", DEFAULT_SECONDS_PER_WORK_MINUTE))
        #: How many tasks the simulator is asked to draw.  A field with eighty
        #: markers in it tells an operator nothing; the scene stays readable and
        #: the rest are still scheduled, just not rendered.
        self.max_visualised = int(settings.get("max_visualised_tasks", 24))

        # The live scenario: HARVEST's own smart strategy, so the live
        # demonstrator behaves like the scenario it demonstrates.  MARL stays
        # off here -- it belongs to the batch simulation, and turning it on
        # would put a second decision-maker in the live loop.
        scenario = main.ScenarioDef(
            name=str(settings.get("scenario", "live")),
            charging_strategy=str(settings.get("charging_strategy", "smart")),
            tractor_pv_enabled=True, load_shedding=True, use_marl=False)
        self.config = main.build_simulation_config(raw_cfg, scenario)
        self.scheduler = main.Scheduler(self.config)
        self._tractors = {tr.tractor_id: tr for tr in self.config.tractors}
        self._tasks = {t.task_id: t for t in self.config.tasks}
        self._day = self.config.start_time.replace(
            hour=0, minute=0, second=0, microsecond=0)

        # Physical reports, per tractor, from whichever simulator is connected.
        self._physical: Dict[str, Dict[str, Any]] = {}
        self._physical_ts: float = 0.0
        self._physical_kind: str = ""
        # Bookkeeping for the transitions this service owns.
        self._arrived_at: Dict[str, float] = {}      # task_id -> clock_min
        self._started_work: Dict[str, float] = {}    # task_id -> clock_min
        self._completed_by: Dict[str, str] = {}      # task_id -> "physical"|"clock"
        # Seeded with the real starting state (no task), so the first tick does
        # not emit a preempt for every idle tractor just to say "still idle".
        self._last_assignment: Dict[str, Optional[str]] = {
            tid: None for tid in self._tractors}
        self._now_min: float = float(self.config.start_time.hour * 60)
        self._prev_clock_min: Optional[float] = None
        self._pending_roll = False
        self._days_rolled = 0
        self._ticks = 0
        self._last_error = ""

        self._thread = threading.Thread(
            target=self._loop, args=(tick_period_s,),
            name="harvest-tasks", daemon=True)
        self._thread.start()

    # ----------------------------------------------------------------- clock --
    def _now(self) -> datetime:
        """The farm clock as a datetime, so HARVEST's task windows apply.

        The live farm advances a time-of-day clock (``grid.clock_min``, minutes
        since midnight, 60x real time); task windows are datetimes on the
        configured day.  Anchoring one to the other is what makes a task's
        window actually open and close while an operator watches.
        """
        return self._day + timedelta(minutes=self._now_min)

    # ------------------------------------------------------------- day roll --
    def _maybe_roll_day(self) -> None:
        """Give the farm a new day's work when the old day is over.

        The live farm clock is a TIME OF DAY that wraps at midnight and runs at
        60x, so a stack left up for an afternoon will run through several farm
        days.  Without this the schedule would be a museum piece: every window
        closed hours ago and nothing ever due again.

        A rollover regenerates the day's tasks through
        :func:`main.build_simulation_config` -- the same authoritative
        task-creation path used at startup -- rather than resetting phases on the
        old objects, so a rolled day is indistinguishable from a fresh start.
        The tractors are NOT rebuilt: they carry live state that is synced from
        the fleet.
        """
        previous = self._prev_clock_min
        self._prev_clock_min = self._now_min
        # ONLY ON THE MIDNIGHT WRAP.  The farm clock is a TIME OF DAY, so the
        # calendar date it belongs to advances exactly when it wraps, and
        # nothing else may advance it: an earlier version also rolled whenever
        # the day's deadlines had all passed, which moved the date forward while
        # keeping the same time of day -- so the new day's windows were in the
        # past too and it rolled again on every tick, for ever.
        #
        # A stack started late in the farm day therefore shows that day's work
        # as missed until midnight, which is the truth about it, and gets a
        # fresh schedule when the clock comes round.
        if not (previous is not None and self._now_min + 30.0 < previous):
            if not self._pending_roll:
                return
        # FINISH WHAT IS IN HAND FIRST.  A tractor half way to a task, or part
        # way through the work, is not something a calendar should cancel: the
        # roll waits until nothing is in transit or executing.  (Measured the
        # other way round once -- three tractors were mid-drive when the clock
        # passed midnight and all three went idle on the spot, which looks like
        # a bug even though the schedule was behaving correctly.)
        in_hand = [task.task_id for task in self._tasks.values()
                   if task.phase in ("TRANSIT", "EXECUTING")]
        if in_hand:
            # Roll on a later tick.  `_pending_roll` remembers that the clock
            # has already wrapped, because the wrap itself happens only once.
            self._pending_roll = True
            return
        self._roll_day()

    def _roll_day(self) -> None:
        import main                                            # noqa: PLC0415

        self._day = self._day + timedelta(days=1)
        self._days_rolled += 1
        self._pending_roll = False
        raw = {**self._raw}
        simulation = {**(raw.get("simulation") or {})}
        start = self._day + timedelta(
            hours=self.config.start_time.hour,
            minutes=self.config.start_time.minute)
        simulation["start_time"] = start.strftime("%Y-%m-%d %H:%M:%S")
        simulation["end_time"] = (
            self._day + timedelta(days=1)).strftime("%Y-%m-%d %H:%M:%S")
        raw["simulation"] = simulation
        fresh = main.build_simulation_config(raw, self.config.scenario_def)

        self.config.tasks = fresh.tasks
        self._tasks = {task.task_id: task for task in fresh.tasks}
        self._arrived_at.clear()
        self._started_work.clear()
        self._completed_by.clear()
        # Nothing is holding a task from the day that just ended.
        for tractor in self._tractors.values():
            tractor.current_task_id = None
        self._last_assignment = {tid: None for tid in self._tractors}

    # ------------------------------------------------------------------ tick --
    def _loop(self, period_s: float) -> None:
        while not self._stop.wait(period_s):
            try:
                self.tick()
            except Exception as exc:                           # noqa: BLE001
                # Reported, never fatal: the task layer is one component of a
                # live stack and must not take the API thread down with it.
                with self._lock:
                    self._last_error = f"{type(exc).__name__}: {exc}"

    def stop(self) -> None:
        self._stop.set()

    def tick(self) -> None:
        """One scheduling cycle: observe, advance, decide, actuate."""
        snapshot = self._runtime.snapshot()
        with self._lock:
            self._ticks += 1
            self._now_min = float(snapshot.grid.clock_min)
            self._maybe_roll_day()
            now = self._now()
            self._sync_from_fleet(snapshot)
            self._advance_phases(now)
            # HARVEST'S OWN SCHEDULER decides everything about assignment.
            self.scheduler.assign_tasks(now)
            commands = self._assignment_commands()
        if commands:
            # Outside the lock: submitting goes to the device layer over the
            # wire, and holding a lock across I/O is how a slow Modbus read
            # becomes a stalled API.
            self._runtime.submit(commands)

    def _sync_from_fleet(self, snapshot: FleetSnapshot) -> None:
        """Mirror the live fleet into the tractor objects the scheduler reads.

        The scheduler scores candidates on SOC, position and charging state, so
        those must be the LIVE values -- from the physical simulator when one is
        connected (its measured pose is the truth about where a tractor is), and
        from HARVEST's own device model otherwise.
        """
        physical = self._fresh_physical()
        for state in snapshot.tractors:
            tractor = self._tractors.get(state.id)
            if tractor is None:
                continue
            tractor.soc_percent = float(state.soc_pct)
            tractor.is_charging = bool(state.charging)
            tractor.is_discharging = bool(state.discharging)
            tractor.enabled = True
            reported = (physical.get(state.id) or {}).get("pose")
            if reported and len(reported) >= 2:
                tractor.location = (float(reported[0]), float(reported[1]))
            elif state.position:
                tractor.location = (float(state.position[0]),
                                    float(state.position[1]))

    def _fresh_physical(self) -> Dict[str, Dict[str, Any]]:
        if time.time() - self._physical_ts > PHYSICAL_STALE_S:
            return {}
        return self._physical

    # ------------------------------------------------------- phase advancing --
    def _advance_phases(self, now: datetime) -> None:
        """Move TRANSIT -> EXECUTING -> DONE from evidence, not from hope.

        Preferred evidence is the physical simulator's: it reports where the
        tractor actually is and how far through the work it actually is.  With
        no simulator connected the same transitions are driven by the farm clock
        and HARVEST's own transit/duration model, so the task layer still
        completes a day's work in `fiware` mode.
        """
        physical = self._fresh_physical()
        for task in self._tasks.values():
            if task.phase not in ("TRANSIT", "EXECUTING"):
                continue
            tractor_id = task.assigned_tractor_id
            tractor = self._tractors.get(tractor_id) if tractor_id else None
            if tractor is None:
                continue
            report = physical.get(tractor_id) or {}
            reported_task = report.get("task_id")

            if task.phase == "TRANSIT":
                arrived = False
                if report and reported_task == task.task_id:
                    arrived = bool(report.get("at_task"))
                    task.transit_progress_pct = float(
                        report.get("transit_progress_pct",
                                   task.transit_progress_pct))
                else:
                    arrived = self._clock_arrival(task, tractor)
                if arrived:
                    task.phase = "EXECUTING"
                    task.transit_progress_pct = 100.0
                    task.progress_pct = 0.0
                    task.started_at = now
                    self._arrived_at[task.task_id] = self._now_min
                    self._started_work[task.task_id] = self._now_min
                continue

            # EXECUTING
            if report and reported_task == task.task_id:
                task.progress_pct = max(
                    task.progress_pct,
                    min(100.0, float(report.get("task_progress_pct", 0.0))))
                done = bool(report.get("task_complete")) or task.progress_pct >= 99.5
                source = "physical"
            else:
                started = self._started_work.get(task.task_id, self._now_min)
                elapsed_min = max(0.0, self._now_min - started)
                duration = max(1.0, float(task.duration_minutes))
                task.progress_pct = min(100.0, elapsed_min / duration * 100.0)
                done = task.progress_pct >= 99.5
                source = "clock"
            if done:
                self._complete(task, now, source)

    def _clock_arrival(self, task: Any, tractor: Any) -> bool:
        """Transit finished according to HARVEST's own transit model."""
        import main                                            # noqa: PLC0415

        distance_m = main.euclidean_distance_m(tractor.location, task.location)
        if distance_m <= self.work_radius_m:
            return True
        speed_m_per_min = self.config.tractors_model.eco_speed_kmh * 1000.0 / 60.0
        needed_min = distance_m / max(1e-6, speed_m_per_min)
        started = task.started_at or self._now()
        return (self._now() - started).total_seconds() / 60.0 >= needed_min

    def _complete(self, task: Any, now: datetime, source: str) -> None:
        """HARVEST declares the task done.  Isaac only ever reports evidence."""
        task.phase = "DONE"
        task.is_done = True
        task.progress_pct = 100.0
        task.completed_at = now
        self._completed_by[task.task_id] = source
        tractor = self._tractors.get(task.assigned_tractor_id or "")
        if tractor is not None and tractor.current_task_id == task.task_id:
            tractor.current_task_id = None
            # The tractor is physically at the task, so that is where HARVEST's
            # model now believes it is.
            tractor.location = (float(task.location[0]), float(task.location[1]))
        task.assigned_tractor_id = task.assigned_tractor_id  # kept for the record

    # ------------------------------------------------------------- actuation --
    def _assignment_commands(self) -> List[Command]:
        """Push HARVEST's decisions into the live fleet, as commands.

        The device/semantic fleet is the system of record for what a tractor is
        doing, so an assignment is not real until it has been submitted through
        FleetInterface like any other actuation -- the same path a human or the
        FIWARE command entity would use.  Only CHANGES are sent.
        """
        commands: List[Command] = []
        for tractor_id, tractor in self._tractors.items():
            current = tractor.current_task_id
            if self._last_assignment.get(tractor_id, "unset") == current:
                continue
            previous = self._last_assignment.get(tractor_id)
            self._last_assignment[tractor_id] = current
            if current:
                commands.append(Command.assign_task(tractor_id, current))
            elif previous:
                # Only when something was actually released; a tractor that was
                # already idle needs no command at all.
                commands.append(Command.preempt_task(tractor_id))
        return commands

    # ------------------------------------------------- physical progress in --
    def report_physical(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Intake for the simulator's physical report (via the ROS 2 bridge).

        Shape (per tractor)::

            {"kind": "isaac", "tractors": {tractor_id: {
                "pose": [x, y], "task_id": str|null, "at_task": bool,
                "transit_progress_pct": float, "task_progress_pct": float,
                "task_complete": bool, "activity": str}}}

        Accepted as EVIDENCE, never as instruction: nothing here assigns,
        creates or cancels a task, and a report about a task the tractor was not
        given is ignored by :meth:`_advance_phases`.
        """
        tractors = payload.get("tractors")
        if not isinstance(tractors, dict):
            return {"accepted": False, "reason": "expected {'tractors': {...}}"}
        with self._lock:
            self._physical = {str(k): dict(v) for k, v in tractors.items()
                              if isinstance(v, dict)}
            self._physical_ts = time.time()
            self._physical_kind = str(payload.get("kind") or "unknown")
        return {"accepted": True, "tractors": len(tractors)}

    # ----------------------------------------------------------- publication --
    def task_goals(self) -> Dict[str, Any]:
        """What the simulator is told: where the work is and how long it takes.

        Everything here is a CONSEQUENCE of HARVEST's decisions.  The simulator
        gets a location, a radius, a state to draw and -- for the task it is
        actually executing -- how many seconds the work should take.  It gets no
        priorities to weigh and no queue to sort.
        """
        with self._lock:
            ordered = self._visualisation_order()
            tasks: Dict[str, Any] = {}
            for task in ordered[:self.max_visualised]:
                state = task_state_from_phase(task.phase, self._missed(task))
                tasks[task.task_id] = {
                    "name": task.name,
                    "location": [round(float(task.location[0]), 2),
                                 round(float(task.location[1]), 2)],
                    "work_radius_m": self.work_radius_m,
                    "state": state,
                    "assigned_tractor": task.assigned_tractor_id,
                    "priority": task.priority,
                    "progress_pct": round(float(task.progress_pct), 1),
                    "work_seconds": round(
                        float(task.duration_minutes) * self.seconds_per_work_minute, 1),
                    # Strong emphasis only for the few tasks that matter now --
                    # a field of eighty equally-bright markers is unreadable.
                    "emphasis": state in ("assigned", "active"),
                }
            assignments = {
                tid: tr.current_task_id
                for tid, tr in self._tractors.items() if tr.current_task_id}
            return {"tasks": tasks, "assignments": assignments,
                    "work_radius_m": self.work_radius_m}

    def _visualisation_order(self) -> List[Any]:
        """Active work first, then what is coming, then history."""
        rank = {"active": 0, "assigned": 1, "pending": 2, "deferred": 3,
                "missed": 4, "completed": 5}
        def key(task: Any) -> Tuple[int, Any]:
            state = task_state_from_phase(task.phase, self._missed(task))
            return (rank.get(state, 9), task.effective_deadline())
        return sorted(self._tasks.values(), key=key)

    def _missed(self, task: Any) -> bool:
        """Window gone and never started: HARVEST's own definition of missed."""
        if task.is_done or task.phase in ("EXECUTING", "TRANSIT"):
            return False
        return self._now() > task.effective_deadline()

    def document(self) -> Dict[str, Any]:
        """The full task document for ``GET /api/tasks`` and Diagnostics."""
        with self._lock:
            now = self._now()
            physical_fresh = bool(self._fresh_physical())
            rows: List[Dict[str, Any]] = []
            for task in self._visualisation_order():
                state = task_state_from_phase(task.phase, self._missed(task))
                rows.append({
                    "id": task.task_id,
                    "name": task.name,
                    "state": state,
                    "phase": task.phase,
                    "priority": task.priority,
                    "location": [round(float(task.location[0]), 2),
                                 round(float(task.location[1]), 2)],
                    "assigned_tractor": task.assigned_tractor_id,
                    "progress_pct": round(float(task.progress_pct), 1),
                    "transit_progress_pct": round(
                        float(task.transit_progress_pct), 1),
                    "duration_minutes": int(task.duration_minutes),
                    "earliest_start": task.earliest_start.isoformat(sep=" "),
                    "latest_finish": task.latest_finish.isoformat(sep=" "),
                    "deadline": task.effective_deadline().isoformat(sep=" "),
                    "completed_by": self._completed_by.get(task.task_id),
                    "interruptions": int(getattr(task, "interruption_count", 0)),
                })
            counts: Dict[str, int] = {state: 0 for state in TASK_STATES}
            for row in rows:
                counts[row["state"]] = counts.get(row["state"], 0) + 1
            return {
                "schema": "harvest-tasks/1.0",
                "clock": now.isoformat(sep=" "),
                "clock_min": round(self._now_min, 1),
                # Which layer is actually driving execution, stated plainly.
                "execution": ("physical" if physical_fresh else "clock"),
                "physical_source": self._physical_kind if physical_fresh else None,
                "scheduler": "main.Scheduler (HARVEST)",
                "day": self._day.date().isoformat(),
                "days_rolled": self._days_rolled,
                "ticks": self._ticks,
                "last_error": self._last_error or None,
                "counts": counts,
                "assignments": {
                    tid: tr.current_task_id
                    for tid, tr in self._tractors.items() if tr.current_task_id},
                "tasks": rows,
            }

    def summary_lines(self, limit: int = 6) -> List[str]:
        """Compact per-tractor lines for Diagnostics.

        e.g. ``tractor_2 -> task_007, travelling, 18 m remaining`` /
        ``tractor_1 -> task_003, working, 62%`` /
        ``tractor_3 -> charger_1, charging``.
        """
        import main                                            # noqa: PLC0415

        with self._lock:
            physical = self._fresh_physical()
            snapshot_chargers = {}
            try:
                snap = self._runtime.snapshot()
                snapshot_chargers = {c.occupied_by: c.id for c in snap.chargers
                                     if c.occupied_by}
                charging = {t.id for t in snap.tractors if t.charging}
            except Exception:                                  # noqa: BLE001
                charging = set()

            lines: List[str] = []
            for tractor_id, tractor in sorted(self._tractors.items()):
                if tractor_id in charging:
                    charger = snapshot_chargers.get(tractor_id, "a charger")
                    lines.append(f"{tractor_id} -> {charger}, charging")
                    continue
                task_id = tractor.current_task_id
                if not task_id or task_id not in self._tasks:
                    lines.append(f"{tractor_id} -> idle")
                    continue
                task = self._tasks[task_id]
                report = physical.get(tractor_id) or {}
                if task.phase == "EXECUTING":
                    lines.append(f"{tractor_id} -> {task_id}, working, "
                                 f"{task.progress_pct:.0f}%")
                else:
                    remaining = main.euclidean_distance_m(
                        tractor.location, task.location)
                    if report.get("distance_to_task_m") is not None:
                        remaining = float(report["distance_to_task_m"])
                    lines.append(f"{tractor_id} -> {task_id}, travelling, "
                                 f"{remaining:.0f} m remaining")
            return lines[:limit]


__all__ = ["LiveTaskService", "PHYSICAL_STALE_S", "DEFAULT_WORK_RADIUS_M"]
